"""Resources: where a file's content comes from — pure data.

A ``Resource`` is a **data descriptor** of a content source (inline bytes, a
host file now; a URL / object-store reference later). It carries **enough info**
for a sandbox to transfer it, but owns **no transfer behavior**: the same
resource is materialized differently by different sandboxes (a host sandbox
copies a ``LocalFile`` into its dir; a remote uploads it), and for some sources
only the sandbox can reach the bytes — so the **receiver decides the transfer**
(ADR-0003 §3). New kinds are added by subclassing (``import``-only); the sandbox
handling them is added alongside (its own, or a built-in that already knows the
kind).
"""

from __future__ import annotations

from dataclasses import dataclass

from etils import epath


class Resource:
  """A file's content source — data only, no transfer behavior (ADR-0003).

  A base for the built-in variants (:class:`Inline`, :class:`LocalFile`) and any
  a consumer adds by subclassing. The receiving sandbox dispatches on the
  concrete kind (see ``Sandbox._mount_one``).
  """


@dataclass(frozen=True, slots=True)
class Inline(Resource):
  """Runtime-generated bytes — a script or expectation built in-process.

  Attributes:
    content: The file's bytes.
  """

  content: bytes


@dataclass(frozen=True, slots=True)
class LocalFile(Resource):
  """A file taken from a host path.

  Attributes:
    path: The host path to read the content from.
  """

  path: epath.Path
